### ISSUE TITLE
Inject in ObjectManager

### ISSUE THREAD

**Issue by sh3r1** [OmarAflak/Dagger2-CYS#2]
Hi! Good Day,

I found your tutorial blog was so very simple and easy to understand specially for beginner like me. But There's a confusion between your tutorial and the code here in github. 

In your tutorial you didn't add any annotation in your ObjectManager, but here in github you have added @Singleton , @Inject annotations.. 

https://github.com/OmarAflak/Dagger2-CYS/blob/master/app/src/main/java/io/causeyourestuck/dagger2/model/ObjectManager.java

Thank you so much.

**Comment by omaraflak** [comment]
Hi, I'm glad I could help.

Yes I changed the code later and didn't mention it in the tutorial. You see, because we actually told to Dagger in `AppModule` how to create `SharedPreferences` and `Gson`, we can simply add the `@Inject` annotation on `ObjectManager`'s **constructor** and it will figure out itself how to build it.

But as it may be confusing for a first time with Dagger, I'm rolling back to the old code. Thanks.

**Comment by omaraflak** [comment]
It's done.
